ARG BASE_IMAGE=public.ecr.aws/bitnami/postgresql:16
FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.title="powerdns-postgresql" \
    org.opencontainers.image.description="Custom PostgreSQL image for PowerDNS platform built from the Bitnami AWS ECR base image"