apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-stack.fullname" . }}-postgres
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-stack.fullname" . }}-powerdns-api
type: Opaque
stringData:
  api-key: {{ .Values.secrets.powerdnsApiKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-stack.fullname" . }}-powerdns-admin
type: Opaque
stringData:
  secret-key: {{ .Values.secrets.adminSecretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-stack.fullname" . }}-powerdns-admin-db
type: Opaque
stringData:
  uri: {{ printf "postgresql://powerdns:%s@%s-postgresql:5432/powerdns" .Values.secrets.postgresPassword .Values.cluster.name | quote }}