apiVersion: v2
name: powerdns-stack
description: Application chart for deploying PowerDNS, PostgreSQL, and PowerDNS Admin through the PowerDNS operator
type: application
version: 0.1.0
appVersion: "1.0"
home: https://github.com/pushpak-23/powerdns-operator
sources:
  - https://github.com/pushpak-23/powerdns-operator
keywords:
  - powerdns
  - dns
  - operator
  - kubernetes
  - postgres
  - admin
maintainers:
  - name: pushpak-23
