{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "powerdns-platform.fullname" . }}-operator
  labels:
    app.kubernetes.io/name: {{ include "powerdns-platform.name" . }}
{{- end }}