apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: powerdns-pdb
  namespace: dns-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: powerdns-platform
